---
- name: install mariadb gpg key
  apt_key: url='http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{ mariadb.gpg_key_id }}' state=present
  # apt_key: keyserver="keyserver.ubuntu.com" id={{ mariadb.gpg_key_id }} state=present # Ansible 1.6

- name: add mariadb deb repository
  apt_repository: repo='deb http://{{ mariadb.mirror }}/mariadb/repo/{{ mariadb.series_version }}/debian {{ debian.version }} main' state=present

- name: install mariadb packages
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - mariadb-server
  notify: restart mariadb

- name: install useful packages
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
  vars:
    packages:
      - python-mysqldb
